name: MineCord3K
version: 0.99.0
author: Eric Edwards
main: io.github.ericedwards.minecord3k.MineCord3KPlugin
api-version: 1.16
commands:
  kit:
    description: Give a player a starting kit
    usage: /<command>
    permission: samplekitplugin.samplekitpluginpermission
  dbc:
    description: Give a player a starting kit
    usage: /<command>
    permission: samplekitplugin.samplekitpluginpermission